In [6]:
import numpy as np
number_of_classes_M = 2
number_of_features_F = 5
initial_weights = np.random.uniform(low=-1, high=1, size = (number_of_classes_M, number_of_features_F))
N = 1000
meanOne = 0.1
meanTwo = 0
stDiv = 1
gdVectorOne = np.random.normal(meanOne, stDiv, size = (N//2, number_of_features_F))
gdVectorTwo = np.random.normal(meanTwo, stDiv, size = (N//2, number_of_features_F))
gdVector = (np.concatenate((gdVectorOne, gdVectorTwo)))
oneHotOne = np.hstack(((np.zeros(N//2)).reshape(N//2,1), (np.ones(N//2)).reshape(N//2,1)))
oneHotTwo = np.hstack(((np.ones(N//2)).reshape(N//2,1), (np.zeros(N//2)).reshape(N//2,1)))
oneHotEn = np.vstack((oneHotOne, oneHotTwo))
random = np.random.permutation(N)
gdVectorMixed = gdVector[random]
oneHotEnMixed = oneHotEn[random]
oneHotEnOne = oneHotEnMixed[:,0].reshape(1000,1)
oneHotEnTwo = oneHotEnMixed[:,1].reshape(1000,1)

In [25]:
for n in range (50):
    eW = np.dot(gdVectorMixed, initial_weights.T)
    eWOne = eW[:,0].reshape(1000,1)
    eWTwo = eW[:,1].reshape(1000,1)
    eWOneCalc = 0.5 * ((eWOne - oneHotEnOne) ** 2)
    eWTwoCalc = 0.5 * ((eWTwo - oneHotEnTwo) ** 2)
    enW = eWOneCalc + eWTwoCalc
    gradient = np.dot(gdVectorMixed.T,(eW - oneHotEnMixed))
    print(gradient.shape)
    stepSize = .00005

    wPrime = initial_weights - (.00005 * gradient).T

print(initial_weights)
print(wPrime)

(5, 2)
[[ 0.17072022 -0.10492489  0.5251751  -0.93961923  0.83756163]
 [-0.41675604  0.23002063  0.22041237 -0.67920973  0.23054583]]
[[ 0.16468738 -0.0996202   0.5016424  -0.89816419  0.7978607 ]
 [-0.39290351  0.22312115  0.21320659 -0.64418131  0.22017766]]


# Problem 2

In [118]:
import numpy as np
import tensorflow as tf
from tensorflow.keras import layers
number_of_feature = 13
number_of_units_in_hidden_layer = 100
#### load the BOSTON regression dataset
(x_train, y_train), (x_test, y_test) = tf.keras.datasets.boston_housing.load_data(path="boston_housing.npz", test_split=0.2, seed=113)
#### pre-process the data
x_train -= np.mean(x_train)
x_train /= np.std(x_train)
x_test -= np.mean(x_test)
x_test /= np.std(x_test)


In [127]:
NN_regression_model = tf.keras.Sequential()
hidden_layer_1 = layers.Dense(units=number_of_units_in_hidden_layer,activation='relu', input_shape= (num_features,)) # define layer
NN_regression_model.add(hidden_layer_1) # add layer
hidden_layer_2 = layers.Dense(units=number_of_units_in_hidden_layer,activation='relu') # define layer
NN_regression_model.add(hidden_layer_2) # add layer
output_layer = layers.Dense(units=1, activation=None) # define layer
(units = 1 for regression)
NN_regression_model.add(output_layer) # add layer


SyntaxError: invalid syntax. Maybe you meant '==' or ':=' instead of '='? (571226105.py, line 7)